[versions]
creative = "0.9.0-SNAPSHOT"
adventure = "4.14.0"

[libraries]
creative-api = { group = "team.unnamed", name = "creative-api", version.ref = "creative" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }